//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activite_Derogation
    {
        public int Id_Activite_Derg { get; set; }
        public Nullable<int> Code_Activite_Derg { get; set; }
        public string Activite_Activite_Derg { get; set; }
        public string Acteurs_Activite_Derg { get; set; }
        public string Temps_prevu_Activite_Derg { get; set; }
    }
}
