//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affect_Derg_Comms
    {
        public int FK_DemDerg_Aff_Com { get; set; }
        public int FK_Commision { get; set; }
        public string detail { get; set; }
    
        public virtual Commission Commission { get; set; }
        public virtual Demande_Derogation Demande_Derogation { get; set; }
    }
}
