//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationModule
    {
        public int ApplicationId { get; set; }
        public int ModuleId { get; set; }
        public string description { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Module Module { get; set; }
    }
}
