//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorisation_Derogation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autorisation_Derogation()
        {
            this.Demande_Derogation = new HashSet<Demande_Derogation>();
        }
    
        public int Id_Autorisation { get; set; }
        public Nullable<System.DateTime> Date_Demande_Autorisation { get; set; }
        public Nullable<System.DateTime> Dae_Avis_Autorisation { get; set; }
        public string Nature_Autorisation { get; set; }
        public Nullable<System.DateTime> Date_Aut_Autorisation { get; set; }
        public Nullable<System.DateTime> Date_Comt_Autorisation { get; set; }
        public string EtatAvancemt_Autorisation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande_Derogation> Demande_Derogation { get; set; }
    }
}
