//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avis_Org
    {
        public int Id_Avis { get; set; }
        public Nullable<int> FK_DemDerg { get; set; }
        public int FK_Organisme { get; set; }
        public int FK_TypAvis { get; set; }
        public string Detail_Avis { get; set; }
    
        public virtual Organisme Organisme { get; set; }
        public virtual Type_Avis Type_Avis { get; set; }
        public virtual Demande_Derogation Demande_Derogation { get; set; }
    }
}
