//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courrier
    {
        public int id_Courrier { get; set; }
        public Nullable<int> Code_Courrier { get; set; }
        public Nullable<System.DateTime> Date_Courier { get; set; }
        public string Source_Courrier { get; set; }
        public string Destination_Courrier { get; set; }
        public string url_Courrier { get; set; }
        public Nullable<int> FK_Nature_Courrier { get; set; }
        public Nullable<int> FK_DemDerg_Cour { get; set; }
    
        public virtual Nature_Courrier Nature_Courrier { get; set; }
        public virtual Demande_Derogation Demande_Derogation { get; set; }
    }
}
