//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande_Derogation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demande_Derogation()
        {
            this.Avis_Org = new HashSet<Avis_Org>();
            this.Courrier = new HashSet<Courrier>();
            this.Document_Derogation = new HashSet<Document_Derogation>();
            this.HistoireDemDergDeletion = new HashSet<HistoireDemDergDeletion>();
            this.parcell = new HashSet<parcell>();
        }
    
        public int Id_DemDerg { get; set; }
        public int Code_DemDerg { get; set; }
        public int NumVersion_DemDerog { get; set; }
        public System.DateTime Date_Arrivee_DemDerg { get; set; }
        public string Intitule_DemDerg { get; set; }
        public double Superficie_Terrain_DemDerg { get; set; }
        public string Maitre_Oeuvrage_DemDerg { get; set; }
        public string Maitre_Oeuvre_DemDerg { get; set; }
        public bool Couverture_DemDerg { get; set; }
        public string PrevisionUrbanistique_DemDerg { get; set; }
        public int Ratio_resid_DemDerg { get; set; }
        public int Ratio_touris_DemDerg { get; set; }
        public int Ratio_indus_DemDerg { get; set; }
        public int Ratio_Social_DemDerg { get; set; }
        public double Montant_Investissement_DemDerg { get; set; }
        public int Emploi_generer_DemDerg { get; set; }
        public int Dero_demande_DemDerg { get; set; }
        public int Duree_realisation_DemDerg { get; set; }
        public string Type_Terrain { get; set; }
        public int Id_Commune { get; set; }
        public string Adresse_DemDerg { get; set; }
        public string Avis_Remarque_DemDerg { get; set; }
        public bool Cloture_DemDerg { get; set; }
        public int FK_DemDerg_Nature_Projet_DemDerg { get; set; }
        public int FK_DemDerg_StatutJuridique_DemDerg { get; set; }
        public int FK_DemDerg_FormeMaitreOeuvrage_DemDerg { get; set; }
        public int FK_DemDerg_Nature_Dem { get; set; }
        public int FK_DemDerg_EtatAvc { get; set; }
        public Nullable<int> Id_Autorisation { get; set; }
        public string Contribution_Projet_DemDerg { get; set; }
        public Nullable<int> Fk_Commission { get; set; }
        public bool Supp { get; set; }
    
        public virtual Autorisation_Derogation Autorisation_Derogation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avis_Org> Avis_Org { get; set; }
        public virtual Commission Commission { get; set; }
        public virtual COMMUNES_RSK COMMUNES_RSK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Courrier> Courrier { get; set; }
        public virtual derogs_demandees derogs_demandees { get; set; }
        public virtual References_Foncieres References_Foncieres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document_Derogation> Document_Derogation { get; set; }
        public virtual EtatAvancement EtatAvancement { get; set; }
        public virtual Forme_MaitreOeuvrage_DemDerg Forme_MaitreOeuvrage_DemDerg { get; set; }
        public virtual Nature_Demande_Derg Nature_Demande_Derg { get; set; }
        public virtual Nature_Projet_DemDerg Nature_Projet_DemDerg { get; set; }
        public virtual Statut_Juridique_DemDerg Statut_Juridique_DemDerg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoireDemDergDeletion> HistoireDemDergDeletion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parcell> parcell { get; set; }
    }
}
