//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Derogation
    {
        public int Id_Doc_Derog { get; set; }
        public Nullable<int> Code_Doc_Derg { get; set; }
        public Nullable<int> Intitule_Doc_Derg { get; set; }
        public string url_Doc_Derg { get; set; }
        public Nullable<int> FK_DemDerg_DocDerg { get; set; }
    
        public virtual Demande_Derogation Demande_Derogation { get; set; }
        public virtual TYPE_DOC TYPE_DOC { get; set; }
    }
}
