//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FicheSuiveuse
    {
        public int Id_FichSuiv { get; set; }
        public Nullable<int> Code_FichSuiv { get; set; }
        public Nullable<System.DateTime> Date_FichSuiv { get; set; }
        public string Debut_FichSuiv { get; set; }
        public string Fin_FichSuiv { get; set; }
        public string TempsRealise_FichSuiv { get; set; }
        public string Visa_FichSuiv { get; set; }
        public Nullable<int> FK_DemDerg_FicheSuiveuse { get; set; }
    
        public virtual Demande_Derogation Demande_Derogation { get; set; }
    }
}
