//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoireStatutDeletion
    {
        public string IdHistoire { get; set; }
        public string FK_Statut { get; set; }
        public string AdminSupp { get; set; }
        public bool Suppression { get; set; }
        public System.DateTime date_heure { get; set; }
    
        public virtual Statuts Statuts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
