//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public System.DateTime heure_date { get; set; }
        public bool Clicked { get; set; }
        public int danger { get; set; }
        public string IdUser { get; set; }
    
        public virtual TypeNotif TypeNotif { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
