//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parcell
    {
        public int objectid { get; set; }
        public string numfoncier { get; set; }
        public string indice { get; set; }
        public Nullable<decimal> xcenteroid { get; set; }
        public Nullable<decimal> ycenteroid { get; set; }
        public System.Data.Entity.Spatial.DbGeometry shape { get; set; }
        public byte[] GDB_GEOMATTR_DATA { get; set; }
        public int Fk_DemDerog { get; set; }
    
        public virtual Demande_Derogation Demande_Derogation { get; set; }
    }
}
