//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCES_RSK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVINCES_RSK()
        {
            this.COMMUNES_RSK = new HashSet<COMMUNES_RSK>();
        }
    
        public int IdProv { get; set; }
        public string Provicne { get; set; }
        public Nullable<int> idreg { get; set; }
        public string Region { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Shape { get; set; }
        public byte[] GDB_GEOMATTR_DATA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMUNES_RSK> COMMUNES_RSK { get; set; }
    }
}
