//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatutRole
    {
        public string StatutId { get; set; }
        public string RoleId { get; set; }
        public bool Lire { get; set; }
        public bool Cree { get; set; }
        public bool Modifier { get; set; }
        public bool Supprimer { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Statuts Statuts { get; set; }
    }
}
