//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionnaireUtilisateurs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Last_Affectation_Com
    {
        public int Id_Commission { get; set; }
        public Nullable<System.DateTime> Date_Commission { get; set; }
        public int FK_Commision { get; set; }
        public int FK_DemDerg_Aff_Com { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public int Id_DemDerg { get; set; }
    }
}
